### PR TITLE
Cherry pick visibilty support from upstream

### PR DESCRIPTION
**Pull request by j-rivero**
Cherry pick the current proposal for C++ visibility support from the upstream github: https://github.com/flexible-collision-library/fcl/pull/233

### CODE REVIEW

**Comment by stonier** [comment]
Can you check the commit that Drake is actually using? I remember it being mentioned it wasn't the tip of fcl. If that's so, then we should try to apply the patch to that.

**Comment by jwnimmer-tri** [comment]
@stonier Are you in progress on setting up reviewable for this repo, or would it help if I did it?

**Comment by stonier** [comment]
For a temporary fork of a repository with cherrypicks from upstream contributions that are still in flight? The detailed reviews should be happening there. It does not seem like the effort would create value here.

I would like some quick pointers on how to set reviewable up with the +feature/+platform review hooks for other repositories sometime though.

**Comment by jwnimmer-tri** [comment]
If detailed review has already happened elsewhere, then the review here would be quick and should not repeat that work.   Merely pulling patches from FCL upstream _master_ would only need a cursory review.  However, if we're _reworking_ the patches when merging them here though, the changes due to rework should be inspected here prior to merge.

In any case, setting up reviewable (1) makes it part of the conventional Drake Developers dashboard, and (2) enforces the feature & platform review process at whatever level of detail is appropriate per the author and reviewers' discretion.

I will send a separate note about setup instructions, since IIRC they are TRI-internally posted.

**Pull request closed without merging**
